export const tags = [
    "Other",
    "Food",
    "Household",
    "Work",
    "Clothing",
    "Hobbies",
    "Family",
    "Numbers",
    "Body",
    "Traveling",
    "Weather",
    "Colors",
    "Traffic",
    "Mathematics",
    "Animals",
    "Emotions",
    "Buildings",

    "Adjectives",
    "Verbs",
]